{{- if not .Values.secret.useExistingSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "citrix-adm-agent.fullname" . }}
  labels:
    {{- include "citrix-adm-agent.labels" . | nindent 4 }}
data:
  db_key.conf: {{ .Values.secret.db_key_conf }}
  private.pem: {{ .Values.secret.private_pem }}
  public.pem: {{ .Values.secret.public_pem }}
  password: {{ .Values.secret.password }}
{{- end }}
