{{- if .Values.cpxConfig.dhkeySecret.mount }}
{{- if not .Values.cpxConfig.dhkeySecret.useExisting }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.cpxConfig.dhkeySecret.secretName }}
data:
  {{ .Values.cpxConfig.dhkeySecret.dhkeyName }}: {{ .Values.cpxConfig.dhkeySecret.dhKey | quote }}
{{- end }}
{{- end }}